[green_agent]
agentbeats_id = "019bb03b-f649-7a41-a26b-82aefef17afc"
env = {
GOOGLE_API_KEY = "${GOOGLE_API_KEY}",  
SERP_API_KEY = "${SERP_API_KEY}", 
SEC_EDGAR_API_KEY = "${SEC_EDGAR_API_KEY}", 
LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = "019bb975-542e-7b12-ab3d-15d288c79fe5"
name = "finance_agent"
env = {
GOOGLE_API_KEY = "${GOOGLE_API_KEY}",  
SERP_API_KEY = "${SERP_API_KEY}", 
SEC_EDGAR_API_KEY = "${SEC_EDGAR_API_KEY}", 
LOG_LEVEL = "INFO" }

[config]
question = "What was Apple's revenue in 2023?"
